= Errors Tracker
:modfile: mod_Errors.pbi

* link:./{modfile}[`{modfile}`^]

[source,purebasic]
--------------------------------------------------------------------------------
include::{modfile}[lines=10]
--------------------------------------------------------------------------------


This module (`Err::`) tracks and handles all errors encountered during the processing stage of the project (validation, extraction, conversion, etc.). Every module that takes part in the Archiv processing should report errors to this module and let the module handle them.

* `Err::TrackError(ErrMessage.s)` -- signal an error and carry on.
* `Err::Abort(ErrorMsg.s, ErrorType)` -- signal a fatal error and request aborting processing the Archiv.

When requesting `Abort()`, the passed `ErrorType` should be one of the following

* `Err::#FATAL_ERR_GENERIC` (default if none specified)
* `Err::#FATAL_ERR_INTERNAL` -- error due to App internals.
* `Err::#FATAL_ERR_FILE_ACCESS` -- App can't get access to file resources.
* `Err::#FATAL_ERR_PANDOC` -- any blocking error related to pandoc.

Before Aborting, the Errors Tracker will ensure that any statistics gathered so far are printed in the final report, so that the user can be made aware of all problems encountred (and not just the last one, which halted processing).

== Required Vars Access

The Errors Tracker needs to access the following vars, which will have to be placed either in its module or in a common module:

[cols=",,",options="header",]
|====================================
|var name |type |namespace
|`FatalErrTypeInfo()` |Array |`Err::`
|`ErrTrackL()` |List |`Err::`
|`currCat` |string |`Err::`*
|`currRes` |string |`Err::`*
|====================================

[NOTE]
================================================================================
`currCat` and `currRes` might be needed by other modules too, so I might need to move them in some common module later on. Since they refer to processing categories, they don't belong in G mod (which some tools might use for processing single resources only, like Codes Checker, etc.), so I should think of creating a module to store project-wide data (categories, etc.).

For now, I just place them in Err mod so I can go ahead with the work, and after all this is the module that deals with tracking processing, so it might even be OK to keep them here.
================================================================================


[[some-considerations]]
== Some Considerations...

The error tracker is intended to gather statistics of any errors encountered during the actual processing of the project, in order to present a detailed report at the end. The way errors are stored should be independent of their final representation (ie: the app's GUI, the debug window, or a log file).

Also, I must keep in mind that the final app might implement a dry-run feature to actually test building the whole project without writing any changes to disk, only in order to check if any errors are encountered with pandoc or at other places. So the error tracker must be able to accomodate that too.

=== The Tracker is For Tools, not Modules?

_Here are some arguments in favor of the fact that the Errors Tracker should be used only by the main tools/apps, not by modules..._

The fact that we have a module dedicated to tracking Errors doesn't mean that _every_ error type should be delegated to the Error Tracker. For example, when <<CodeArchiv Module,mod CodeArchiv>> carries out its Integrity Checks, the number of errors found are stored in `Arc::info\Errors`, and a report is stored in `Arc::info\IntegrityReport`, which will contain details of every error (if any). In this case, there seems to be no need for this type of check to rely on the Errors Tracker, for we're dealing with basic initialization of the CodeArchiv (project and module). Most tools will probably just need to know if the Archiv is ready for being processed, and the above vars suffice for this.

Usually, a tool will consider the Error Tracker as a way to track errors encountered during the main steps which the tool is specifically designed to perform, so that it can be produce a detailed custom report at the end. Modules initialization failures (like the example above) are subsidiary to the tool tasks, and instead of having those initialization procedures communicate directly with the Error Tracker, it should be up to the tool to decide if to include these errors and how.

In other words: the Tracker should be fully controlled by the app/tool, not by the single modules; the latter should store their errors internally, and offer an interface to the main tool for examining such errors, but it's up to the main tool to fully control the Tracker.

The next section shows the complications that derive from having the modules use the Tracker -- ie, the modules would have to register themselves with the Tracker in order to be managed.

=== Should Modules Register Themselves with mod Errors?

_Here are some considerations of the complications that would arise if the Tracker was to be used by modules too...._

Ideally, each module should store information about its errors, but the <<Errors Tracker,Errors Tracker>> module has to also track all the errors of all the modules, so that it can print out to the user/tool a report on all the errors encountered at any stage (wether it's just an integrity check stage or an actual attempt to build the HTML pages).

Probably, I'll have to devise a way to allow each module to "`register`" itself with the <<Errors Tracker,Errors Tracker>> at initialization time (like Sicro is doing with the logger module), so that the Errors module is able to handle errors from various modules separately (internally) and at the same time produce unified error reports from all modules.

After all, different tools might use some modules and not others (eg, the Code Checker for single resources will not need the CodeArchiv module), so the Errors module shouldn't make assumptions about which modules will be present during use.

This topic introduces another need too, that of some global initialization system (via mod G) that allows all modules to initialize themselves according to other modules included by the app, and their settings. This might be especially true for the Errors and Logger modules. I should think of some simple way to handle registering modules via mod_G.

// EOF //
