
= Problems Ahead

== Issues With Resource Files

There are some issues in dealing with resource files which require some thoughts in order to be implemented smartly, especially since they deal with functionality that will be shared by different apps.

Depending on the type of resource file, the number of operations that could be carried out on the resource may vary.

[cols=",,,,",options="header",]
|===============================================================================
| res type        | alidate header | check EOF settings | `--check --thread` | `IsMainFile` block

| `<file>.pb`     | always | always  |always  | _never_
| `<incfile>.pbi` | always | always  |always  | always
| `CodeInfo.txt`  | always | _never_ |_never_ | _never_
|===============================================================================

This brings to attention the fact that with include files (`.pbi`) there is a potential redundancy of file access if we were to keep separate functions for header comments parsing, checks for the presence of PB settings in the file and checks for a `#PB_Compiler_IsMainFile` block.

Ideally, we could access the resource file just once:

1.  Extract the raw header comments block (and store it to memory)
2.  Check if PB settings are stored inside the file
3.  Check that a `*.pbi` resource has a `#PB_Compiler_IsMainFile` block



This could be carried out indepedently of the desired actions -- ie, the module dealing with resource files should carry out the above steps whenever it receives a request to do something with a given resource.

The downside of this approach is that any tools that don't wish to carry out all the checks might end up having some overhead due to this (potentially, steps 2 and 3 are the more time consuming ones).

Alternatively, the module could allow the user to register the intended actions he will need for any resource -- ie, before actually carrying any of them out -- so the module can smartly prefetch/preprocess the resource file accordingly.

This is worth considering, especially in view of the implementation of a cache system. In both cases, it's important that the module has some independent way of controlling file access, imposing a separation between the required actions on the resource and how and when the resource is accessed on disk. The tool should only worry about requesting to the module's API that the various checks are carried out, and leave it entirely to the module to decide when and how the resource should be retrived from disk, allowing therefore the module the freedom to prefetch data and store it to memory when this would prevent redundant disk accesses.

What emerges from these considerations is that all functionality dealing with resources is likely to be better handled by a single module -- even if some tools will not use all of them.

=== Memoization: A Possible Solution

The above mentioned issues could be resolved by employing momization in the module's procedures: if the resource has already been parsed, the stored data is returned instead of carrying out the full process of accessing the resource and extracting the data.

This does not solve the general problem of wehter or not any attempt to check a resource for a specific problem should make the module prefetch all potentially needed data. This second aspect could be handled by some settings passed to the module, to inform it of what checks the tools will carry out in the context -- eg., a tool might inform the res module that it's not interested in dealing with PB settings that might be stored in the source file, but only with parsing header comments; in this case the module will not attempt to handle the in-file settings and memoize them. And so on.

These two solutions together could optimize both the issue of redundant file access, as well as provide a single reusable module for all tools that will not carry out unnecessary actions.

The details of how these are going to be implemented are yet to be established, but they should not affect they module's API nor create problems when a cache system is introduced in the main code of the HTML Generator (file caching should filter invocations of the res module, and therefore not affect the res module's public interface).

With this in mind, I should start to move all resource related functionality to an independent module, even if it doesn't take care of optimizations at the onset -- as long as it won't break its usage when these are introduced.

// EOF //
