
= Notes on Modules Usage

Since the whole purpose of splitting the app into modules, here are some important notes on how the modules should be used in custom tools for this project.

== Global Enumerators

Dynamic numbering of PB "`objects`" via `#PB_Any` works on a global scale, even when using modules; so, to avoid conflicts when creating RegExs, files, gadgets, etc., enumerations should be tracked globally by the G module.

For example, link:./mod_G.pbi[`mod_G.pbi`^] defines in its public module interface:

[source,purebasic]
----
Enumeration RegExsIDs
EndEnumeration
----

Where `RegExsIDs` is a common RegEx Enumeration Identifier to keep track of the RegExs ID across modules, otherwise Enums will start over from 0 and overwrite existing RegExs! Other modules' Enums will take on from there by using:

[source,purebasic]
----
Enumeration G::RegExsIDs
----

This system allows working with enumerated "`object`" without conflicts, and to use constants instead of vars to refer to the various RegExs, files, gadgets, etc.

It also means that any third party tools willing to reuse some of the modules of this project will need to adhere to this enumeration scheme.


// EOF //
